### ISSUE TITLE
Error: gem install logstash-input-dynamodb:'< 2' logstash-filter-dynamodb:'< 2'

### ISSUE THREAD

**Issue by chiukit** [mantika/dockerfiles#3]
When I try to use 1.5.6 Dockerfile and build it. The following error occurs:

Step 6 : RUN gem install logstash-input-dynamodb:'< 2' logstash-filter-dynamodb:'< 2'
 ---> Running in d76aaf74d591
ERROR:  While executing gem ... (Gem::DependencyResolutionError)
    conflicting dependencies logstash-core (<= 2.3.0.snapshot3, >= 2.0.0) and logstash-core (< 2.0.0, >= 1.4.0)
  Activated logstash-core-1.5.0
  which does not match conflicting dependency (<= 2.3.0.snapshot3, >= 2.0.0)

  Conflicting dependency chains:
    logstash-input-dynamodb (< 2), 1.0.0 activated, depends on
    logstash-core (< 2.0.0, >= 1.4.0), 1.5.0 activated

  versus:
    logstash-input-dynamodb (< 2), 1.0.0 activated, depends on
    logstash-codec-json (>= 0), 2.1.4 activated, depends on
    logstash-core-plugin-api (~> 1.0), 1.0.0 activated, depends on
    logstash-core (<= 2.3.0.snapshot3, >= 2.0.0)

The command '/bin/sh -c gem install logstash-input-dyn

**Comment by marcosnils** [comment]
@kit1989 seems like it stopped working. I believe someone updated a third party dependency and this broke. 

I'll check it out tonight. Thx for reporting.

**Comment by marcosnils** [comment]
@kit1989 it's fixed now. Can you please try again and close this issue if it works for you?

**Comment by chiukit** [comment]
Working now. Thanks!
